name: Genealogy & Gardening
favicon: null
layout_spectrum: 0.88682
typography_spectrum: 0.62147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1c17'
    - '#104a21'
    - '#3dbb2c'
    - '#229b10'
    - '#84d56c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
